### ISSUE TITLE
Null handling in JSON decoding

### ISSUE THREAD

**Issue by istreeter** [DouglasConnect/edelweiss-data-python#11]
We use several different styles for decoding json:

Style 1 [e.g. here in Column](https://github.com/DouglasConnect/edelweiss-data-python/blob/master/edelweiss_data/api.py#L422)

```description=d['description'],```

This will give a KeyError if description is not in the json object.  Note that description is an optional field.  I guess this is safe because our json objects have explicitly `"description": null` if description is not set.  But is it safe to rely on that field always being present?

Style 2 [e.g. here in PublishedDataset](https://github.com/DouglasConnect/edelweiss-data-python/blob/master/edelweiss_data/api.py#L751)

```schema=Schema.decode(d['schema']) if ('schema' in d and d['schema']) else None```

Here we are guarding against schema not being in the json object.  But schema is a required field for PublishedDataset, so why are we guarding against this?  Would it be better to raise an exception here if schema is not set?

Style 3 [e.g. here](https://github.com/DouglasConnect/edelweiss-data-python/blob/master/edelweiss_data/api.py#L756)

```is_public=d['isPublic'] if 'isPublic' in d else None,```

This could be written more concisely as `d.get('isPublic')`.  But note again `isPublic` should be a required field, so maybe it is better to call `d['isPublic']` and to raise a KeyError if it is missing from the json.

**Comment by matijapretnar** [comment]
I think you shouldn't be defensive about required fields. Style 2 should be used for InProgressDataset schemas, but for PublishedDatasets I guess it was a lazy copy-paste.

**Comment by danyx23** [comment]
Yeah I think unifying this somewhat is good. Agree that we don't have to guard against missing fields when the field is not optional but case 1 should only be used if the field is indeed mandatory

**Comment by istreeter** [comment]
The [tests are failing](https://github.com/DouglasConnect/edelweiss-data-python/runs/621803341), and I see now why were using style 2 even for PublishedDataset.

The test error is `KeyError: 'schema'` when we call `api.get_published_datasets(condition=datasets_filter)`

It is because our dataset query takes parameters like `IncludeSchema : bool` and `IncludeMetadata : bool`.  So the list received by the client cannot be decoded as a PublishedDataset *if* we are strict about decoding.

We could be pragmatic and go back to style 2 i.e.

```schema=Schema.decode(d['schema']) if ('schema' in d and d['schema']) else None```

But.... we should also think about whether our F# code needs to handle this situation.  Does the F# client need a `PartialPublishedDataset` type, so there is a convenient type to decode into?

**Comment by danyx23** [comment]
Yeah let's make sure this works in all cases. Also +1 to adding this to the F# client.
