### ISSUE TITLE
Merge the 3 update dataset endpoints

### ISSUE THREAD

**Issue by istreeter** [DouglasConnect/edelweiss-data-python#7]
This corresponds to [issue 305](https://github.com/DouglasConnect/edelweiss/issues/305) from the edelweiss server repo.

**Comment by istreeter** [comment]
@matijapretnar @danyx23 I made a PR (#8) for changing the python client to _mainly_ use the generic update method for a InProgressDataset.

However, I do not know what to do about the follow methods:
* [upload_schema_file](https://github.com/DouglasConnect/edelweiss-data-python/blob/be4bf62c65d8eccefcbfcbc9a7d272c9c4d88e6b/edelweiss_data/api.py#L613)
* [upload_metadata_file](https://github.com/DouglasConnect/edelweiss-data-python/blob/be4bf62c65d8eccefcbfcbc9a7d272c9c4d88e6b/edelweiss_data/api.py#L630)

Currently the python client does not attempt to deserialize the file content from json - and in some ways that is quite nice. Instead, it POSTs the file content directly.

In order to use the generic update method we would need to deserialize the file content so that we can properly create the request payload of the update endpoint.  This is possible, of course.  But is it a good idea?

Is there an argument that we should continue POSTing file content without modification?  Do we allow the python client to continue using the specialist upload-schema and upload-metadata endpoints on the server?  In which case I should un-deprecate them on the server.

**Comment by istreeter** [comment]
@matijapretnar @danyx23 A reminder about this question that I wrote a few weeks ago 👆

I had forgotten I wrote this, but the questions are still valid and not resolved.

**Comment by matijapretnar** [comment]
I don't see a harm in deprecating both and deserializing the file to create a payload. I don't think direct upload buys anything except a miniscule time saving.

**Comment by danyx23** [comment]
I agree with Matija - I think it's actually beneficial if you get feedback about an invalid file early on.
